# Generated by Django 5.1.4 on 2024-12-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('distributor', 'Independent Distributor/Representative'), ('team_leader', 'Team Leader'), ('recruiter', 'Recruiter'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
