# Generated by Django 5.1.4 on 2024-12-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='referral',
            new_name='referral_code',
        ),
    ]
